#!/usr/bin/env bash

set -e

if [ ! -f /usr/local/bin/uv ]; then
    echo "==> Installing uv"
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

echo "==> Creating venv"
uv venv -p 3.10 .gladly

echo "==> Activating venv"
source .gladly/bin/activate

echo "==> Installing packages"
uv pip install -r requirements.txt

echo "==> Creating jupyter kernel"
python -m ipykernel install --user --name=.gladly --display-name="Python 3.10 (.gladly)"
